import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ENV_FILENAME = ".env";

/**
 * Parse .env file content into key-value pairs.
 * Supports: KEY=VALUE, KEY="VALUE", KEY='VALUE', # comments, blank lines.
 */
export function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) {
      continue;
    }
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();
    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Serialize key-value pairs to .env format.
 * Quotes values that contain spaces, #, or quotes.
 */
export function serializeEnvFile(vars: Record<string, string>): string {
  const lines: string[] = ["# Generated by The Engineer. Do not commit to version control."];
  for (const [key, value] of Object.entries(vars)) {
    if (value.includes(" ") || value.includes("#") || value.includes('"') || value.includes("'")) {
      lines.push(`${key}="${value.replace(/"/g, '\\"')}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }
  lines.push(""); // trailing newline
  return lines.join("\n");
}

/**
 * Load ~/.engineer/.env into process.env.
 * Existing env vars take precedence (never overwritten).
 * No-op if file does not exist.
 * Returns the set of var names that were loaded.
 */
export function loadEnvFile(engineerHome: string): Set<string> {
  const filePath = join(engineerHome, ENV_FILENAME);
  if (!existsSync(filePath)) {
    return new Set();
  }

  const content = readFileSync(filePath, "utf8");
  const vars = parseEnvFile(content);
  const loaded = new Set<string>();

  for (const [key, value] of Object.entries(vars)) {
    if (process.env[key] === undefined) {
      process.env[key] = value;
      loaded.add(key);
    }
  }

  return loaded;
}

/**
 * Write secrets to ~/.engineer/.env with 0o600 permissions.
 * If file exists, merges (new values override existing for same key).
 */
export function writeEnvFile(engineerHome: string, secrets: Record<string, string>): void {
  const filePath = join(engineerHome, ENV_FILENAME);
  let existing: Record<string, string> = {};

  if (existsSync(filePath)) {
    existing = parseEnvFile(readFileSync(filePath, "utf8"));
  }

  const merged = { ...existing, ...secrets };
  writeFileSync(filePath, serializeEnvFile(merged), { encoding: "utf8", mode: 0o600 });
}

/**
 * Check .env file permissions. Returns null if OK, warning string if too open.
 */
export function checkEnvFilePermissions(engineerHome: string): string | null {
  const filePath = join(engineerHome, ENV_FILENAME);
  if (!existsSync(filePath)) {
    return null;
  }

  const stat = statSync(filePath);
  const groupOtherBits = stat.mode & 0o077;
  if (groupOtherBits !== 0) {
    return `.env file has overly permissive permissions (${(stat.mode & 0o777).toString(8)}). Expected 600.`;
  }
  return null;
}
