import { readFileSync, readdirSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { ALL_PLUGIN_DOCS } from "../../../../src/cli/bundled/plugin-docs.js";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const DOCS_PLUGINS_DIR = join(REPO_ROOT, "docs", "plugins");

function listMarkdownFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listMarkdownFiles(fullPath));
    } else if (entry.name.endsWith(".md")) {
      files.push(fullPath);
    }
  }
  return files;
}

function toPosixRelative(absolutePath: string): string {
  return relative(REPO_ROOT, absolutePath).split(sep).join("/");
}

// The bundle is generated by scripts/gen-bundled-docs.ts; these tests are the runtime guard that the
// committed file still mirrors source exactly. CI also fails if `pnpm run docs:bundle` produces a diff.
describe("ALL_PLUGIN_DOCS bundle", () => {
  it("contains exactly the markdown files under docs/plugins/", () => {
    const sourcePaths = listMarkdownFiles(DOCS_PLUGINS_DIR).map(toPosixRelative).sort();
    const bundledPaths = ALL_PLUGIN_DOCS.map((doc) => doc.relativePath).sort();
    expect(bundledPaths).toEqual(sourcePaths);
  });

  it("mirrors each source file byte-for-byte (no drift, no mis-escape)", () => {
    for (const doc of ALL_PLUGIN_DOCS) {
      const source = readFileSync(join(REPO_ROOT, doc.relativePath), "utf8");
      expect(doc.content, `bundled "${doc.relativePath}" differs from its source file`).toBe(source);
    }
  });
});
